apiVersion: v1
kind: Namespace
metadata:
  name: monitor-stock

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitor-stock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # Ensure this matches your StorageClass

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitor-stock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # Ensure this matches your StorageClass

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: monitor-stock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust size as needed
  storageClassName: standard  # Ensure this matches your StorageClass

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitor-stock
data:
  grafana.ini: |
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    user = nilesh.k@sigmoidanalytics.com
    password = 
    skip_verify = true
    from_address = nilesh.k@sigmoidanalytics.com
    from_name = Grafana
    ehlo_identity = grafana.example.com

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitor-stock
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'metrics_collector'
        static_configs:
          - targets: ['metrics_collector:7878']
