apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nileshkishore/stock-frontend:5
        env:
        - name: CHANGE
          value: "-2.5"
        - name: NEXT_PUBLIC_API_URL
          value: "http://192.168.58.2:30000"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: stock
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001 
  selector:
    app: frontend

