apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
      - name: metrics-collector
        image: nileshkishore/stock-metrics_collector:1
        env:
        - name: DEBUG
          value: "1"
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "first_database"
        - name: DB_USER
          value: "postgres_user"
        - name: DB_PASSWORD
          value: "1234"
        ports:
        - containerPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
  namespace: stock
spec:
  type: NodePort
  ports:
  - port: 7878
    targetPort: 7878
    nodePort: 30003 
  selector:
    app: metrics-collector

